### ISSUE TITLE
Parsing list at pokemon.py:27 seems to be starting with the last element, causing index errors

### ISSUE THREAD

**Issue by MatthewOwens** [Xemerau/PyProject#3]
Not sure what's causing this, need to look into the enumerate function in more detail

**Comment by Noble-Code** [comment]
I've half fixed this but it seems to be filling one entry of the tuple with the index twice. Once i've sorted that it should work correctly
- edit: fixed this now, pokemon should load correctly

**Comment by MuttonChopDavo** [comment]
Use sandstorm. It's super effective!

**Comment by MuttonChopDavo** [comment]
Is it really closed?
